### ISSUE TITLE
Sheets session #1 wrapup

### ISSUE THREAD

**Issue by michael** [stencila/stencila#125]
I just had a look at the SheetWriter and discovered that I've missed a major issue with the new modularized component implementations (see #124).

Sorry for that. I will look into it asap and do a bit of more UI testing to make sure you have a demoable version.

Things like integrating the Ace editor (for expression editing) and Substance HTML editor (for rich text) we need to push to another session. I will open a separate ticket.

Remaining issues:

- [x] #124 cell updates don't work
- [x] #120 Verify Nokome converter fixes
- [x] #116 Nokome pls confirm
- [x] #109 disambiguate HTML format
- [x] #128 double click for editing does not work properly
- [x] #129 wrong typeover behavior

**Comment by nokome** [comment]
Thanks @michael . I think #118 (cell mapping) should be moved into a  #127 (Sheets session 2) - it is quite a lot of work in both front-end and back-end.

**Comment by michael** [comment]
Moved #118 to #127 . @nokome can you just check if #120 works for you now that we updated the Substance version?

I think then we are good to call session 1 finished. Please close the issue when you agree. :)

**Comment by nokome** [comment]
@michael having some problems checking #120  right now; will try to confirm/deny it works in the next couple of days

**Comment by nokome** [comment]
OK, #120 closed, so closing this now

**Comment by michael** [comment]
we somehow cant connect to the hangout.

> On Feb 12 2016, at 8:32 pm, Nokome Bentley &lt;notifications@github.com&gt;
wrote:  

>

> Closed [#125](https://github.com/stencila/stencila/issues/125).

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/stencil
a/stencila/issues/125#event-548962030).![](https://github.com/notifications/be
acon/AAALcyo8DB6QQ47si1xr-_GyemQg-7_nks5pjirOgaJpZM4HPDOK.gif)
