### ISSUE TITLE
Sheets session #2

### ISSUE THREAD

**Issue by michael** [stencila/stencila#127]
Things we should work on in a next session. Need to discuss when that could be.
- [ ] #132 better session lifecycle, save workflow and optimizations (Nokome)
- [ ] #115 Integrating Ace editor for expression editing (Substance)
- [ ] #117 Activate rich text editing (Substance)
- [ ] #126 Overhaul UI (Substance)
- [ ] #118 Cell mapping (Nokome)

In the meantime Nokome could work on:
- stabilising the backend
- Supporting HTML as primitive values (and find a way to serialize them e.g. as Markdown in the TSV)
- Recording bugs with the current UI
- Work on a priority list on what to tackle next
