### ISSUE TITLE
meta(ui): stocktake of user interface designs

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2027]
### Summary

This is a meta-issue to take stock of existing and soon-to-be-required user interface designs and implementations. This will allow us to create separate issues for the design and implementation of each element. I suggest that, when we create those issues, we edit this issue to add a link to the new issue next to the relevant item below.

We also need to organize the Figma project so it is easier to know where to go when implementing a design and so it easier to do this, and future stock takes. In addition, we need to wire together some (most?) of the designs into mocks workflows so that we can test some of our key assumptions.

This issue is organized into "areas" of the overall user interface. This organization is up for discussion but whatever we settle on, I suggest that the Figma project be organized similarly.

* [Application chrome](#Applicationchrome)
	* [Writer app chrome](#Writerappchrome)
		* [Status UI](#StatusUI)
		* [Navigation UI](#NavigationUI)
		* [Document collaboration UI](#DocumentcollaborationUI)
		* [Config UI](#ConfigUI)
	* [Reader app chrome](#Readerappchrome)
		* [Status UI](#StatusUI-1)
		* [Navigation UI](#NavigationUI-1)
* [Editor chrome](#Editorchrome)
	* [Source editor](#Sourceeditor)
		* [Document node information and interaction](#Documentnodeinformationandinteraction)
		* [Editor config](#Editorconfig)
	* [Visual editor](#Visualeditor)
* [Node display and interaction](#Nodedisplayandinteraction)
	* [Prose](#Prose)
		* [Block prose](#Blockprose)
		* [Inline prose](#Inlineprose)
	* [Code](#Code)
		* [Block code](#Blockcode)
		* [Inline code](#Inlinecode)
	* [Math](#Math)
		* [Block math](#Blockmath)
		* [Inline math](#Inlinemath)
	* [Style](#Style)
		* [Block style](#Blockstyle)
		* [Inline style](#Inlinestyle)
	* [Flow](#Flow)
		* [Block flow](#Blockflow)
		* [Inline flow](#Inlineflow)
	* [Edits](#Edits)
		* [Block instructions and suggestions](#Blockinstructionsandsuggestions)
		* [Inline instructions and suggestions](#Inlineinstructionsandsuggestions)
	* [Works](#Works)
		* [Block works](#Blockworks)
		* [Inline works](#Inlineworks)
	* [Data](#Data)
		* [Data values](#Datavalues)
		* [Data validators](#Datavalidators)
	* [Other](#Other)

## <a name='Applicationchrome'></a>Application chrome

The UI elements around the outside of an app. We need two apps: one for users writing (i.e. creating) projects/documents (the writer app; what we currently have) and one for users reading (i.e. consuming) projects/documents (here "project" just means a folder of documents that you might want to publish as a "site").

### <a name='Writerappchrome'></a>Writer app chrome

An app for users writing (i.e. creating) projects/documents.

- [x] General layout of the app

#### <a name='StatusUI'></a>Status UI

For things related to the status of user and the app:

- [x] Current user, sign in, sign out (_Am I logged in? as who? how do I sign in? how do I sign out?_)
- [x] Connection status (_Am I connected? is it trying to reconnect?_)

#### <a name='NavigationUI'></a>Navigation UI

For navigating around the app, opening different views of the project/folder and documents, etc (currently in the left sidebar):

- [~] Project browser (_I want to find a file and open it, i want to create/delete/move/rename a folder/file_; exists but needs design/usability audit)
- [x] Visual editor button (_I want to edit this document in a Google Docs like editor_)
- [x] Source editor button (_I want to edit this document using Markdown (or other text format)_)
- [x] Split view button (_I want to edit this document using Markdown (or other text format) **and** have a preview to the side_)
- [x] Config button (_I want to change some setting in the configuration of the app_)

#### <a name='DocumentcollaborationUI'></a>Document collaboration UI

For collaborating on a document with others:

- [x] Current collaborators on the document (_Who else is working on this project/document right now?, what format are they using?, where is their cursor located in the document?_)
- [ ] Document sharing and permissions (_I want to make a person a collaborator on a document with certain access permissions_)

#### <a name='ConfigUI'></a>Config UI

For changing configuration settings of the app. Here for completeness but I don't think we should spend time on designs here. Rather, I think we should use something like [this](https://github.com/json-schema-form-element/jsfe) to take a JSON Schema specification of the config and automatically generate a form for it. The design input required here will be to audit the generated UI for usability and consistency with the rest of the app.

### <a name='Readerappchrome'></a>Reader app chrome

For users reading (i.e. consuming) projects/documents.

#### <a name='StatusUI-1'></a>Status UI

For things related to the status of the user and the app:

- [ ] Current user, sign in, sign out (as for writer app, probably the same UI)
- [ ] Connection status (as for writer app, probably the same UI)

#### <a name='NavigationUI-1'></a>Navigation UI

For navigating between documents within a project, and between sections with a document:

- [x] Project browser (_I want to see what documents are in a project and jump between them_)
- [x] Document browser (_I want to see what sections are in a document and jump between them_)

## <a name='Editorchrome'></a>Editor chrome

The UI elements around the outside of an editor. We need two editors: one for users writing documents using a source format (e.g. Markdown; the current `SourceView`) and one for users using a WYSIWYG editor (e.g.the current `VisualView`)

#### <a name='Documentnodeinformationandinteraction'></a>Document node information and interaction

Source formats such as Markdown are unable to represent the all the properties of a document node. For example, a `CodeChunk` has properties such as `executionDependencies` (the other nodes in the document it depends upon) and `executionMessages` (e.g. any errors) which are not represented in the Markdown source. For this reason we provide additional ways to view and interact with (i.e. edit) document nodes.

- [x] Gutter displaying `Block` node types (e.g. `InstructionBlock`) (_I want to quickly see what block node type is associated with each line so I can click to find more information about them_)
- [ ] Background colours and hover icons displaying `Inline` node types (e.g. `CodeExpression`) (_I want to quickly see what inline node types are in a paragraph so I can differentiate them from text and click to find more information about them_)
- [~] Syntax highlighting Markdown extensions for node type (have this but needs a audit for consistency of colours and other styling with other UI e.g. gutters)
- [ ] Gutter displaying the [execution status](https://github.com/stencila/stencila/blob/main/docs/reference/schema/flow/execution-status.md) (e.g. `Running`, `Succeeded`, `Failed`, `Cancelled`) of executable nodes (both block and inline) associated with each line (_When I execute a node, or all the nodes in a document, I want to know that it is running and whether or not it succeeded_)
- [~] Sidebar displaying node "cards" for further information/interaction (we have a rudimentary version of this now, layout needs to be improved)

#### <a name='Editorconfig'></a>Editor config

For changing the display of the editor:

- [x] Format switcher
- [x] Toggle line wrapping
- [x] Toggle node type gutter
- [x] Toggle node status gutter
- [ ] Toggle node information/interaction sidebar
- [x] Breadcrumbs showing current node hierarchy

### <a name='Visualeditor'></a>Visual editor

TODO

## <a name='Nodedisplayandinteraction'></a>Node display and interaction

The UI elements for viewing more information about a node (e.g. authors, execution status) and interacting with them (e.g. editing code in `CodeChunk`s, editing TeX in `MathBlock`s, executing a node by pressing the play button, accepting the suggestion made by an AI assistant). Each of these node types will need specific designs due to the varying properties that they have. Some node types are very simple and there is little additional information to display beyond authors (e.g. `Paragraph`, `Heading`), others require simple edit interactions (e.g. editing the `code` property of a static `CodeBlock`), others require complex interactions and have nested nodes (e.g. editing and executing a `CodeExpression` within a paragraph, accepting or rejecting suggestions with an `InstructionBlock`).

Our current approach is to develop a single Web Component for each node type and then alter its appearance as appropriate to the current view (e.g. hiding the code in a `CodeChunk` when in `SourceView` for Markdown because it is already in the editor). Designs should consider this and, where necessary, provide alternative variants for each view.

The following is a list of node types, by [category](https://github.com/stencila/stencila/tree/main/docs/reference/schema), for which we will need UI for display and/or interaction (it excludes most simple node types only have `content` e.g `Emphasis`).

### <a name='Prose'></a>Prose

Node types used for structuring prose:

#### <a name='Blockprose'></a>Block prose

- [ ] [`Admonition`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/prose/admonition.md)
- [ ] [`Heading`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/prose/heading.md)
- [ ] [`List`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/prose/list.md)
- [ ] [`Note`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/prose/note.md)
- [ ] [`Paragraph`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/prose/paragraph.md)
- [ ] [`QuoteBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/prose/quote-block.md)
- [ ] [`Section`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/prose/section.md)

#### <a name='Inlineprose'></a>Inline prose

- [ ] [`Cite`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/prose/cite.md)
- [ ] [`Link`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/prose/link.md)

### <a name='Code'></a>Code

Node types containing static or executable code:

#### <a name='Blockcode'></a>Block code

- [ ] [`CodeBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/code/code-block.md)
- [ ] [`CodeChunk`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/code/code-chunk.md)

#### <a name='Inlinecode'></a>Inline code

- [ ] [`CodeInline`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/code/code-inline.md)
- [ ] [`CodeExpression`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/code/code-expression.md)

### <a name='Math'></a>Math

Node types containing math:

#### <a name='Blockmath'></a>Block math

- [ ] [`MathBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/math/math-block.md)

#### <a name='Inlinemath'></a>Inline math

- [ ] [`MathInline`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/math/math-inline.md)

### <a name='Style'></a>Style

Node types for styling content including dynamically (e.g. coloring a block based on the value of a variable):

#### <a name='Blockstyle'></a>Block style

- [ ] [`StyledBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/style/styled-block.md)

#### <a name='Inlinestyle'></a>Inline style

- [ ] [`StyledInline`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/style/styled-inline.md)

### <a name='Flow'></a>Flow

Node types for controlling execution flow within a document:

#### <a name='Blockflow'></a>Block flow

- [x] [`ForBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/flow/for-block.md)
- [x] [`IfBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/flow/if-block.md)
- [ ] [`IncludeBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/flow/include-block.md)
- [ ] [`CallBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/flow/call-block.md)

#### <a name='Inlineflow'></a>Inline flow

- [ ] [`Parameter`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/flow/parameter.md)
- [ ] `IfInline` ([in development](https://github.com/stencila/stencila/issues/2024))

### <a name='Edits'></a>Edits

Node types for issuing editing instructions and managing suggestions:

#### <a name='Blockinstructionsandsuggestions'></a>Block instructions and suggestions

- [ ] [`InstructionBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/edits/instruction-block.md)
- [ ] [`InsertBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/edits/insert-block.md)
- [ ] [`ReplaceBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/edits/replace-block.md)
- [ ] [`DeleteBlock`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/edits/delete-block.md)

#### <a name='Inlineinstructionsandsuggestions'></a>Inline instructions and suggestions

- [ ] [`InstructionInline`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/edits/instruction-inline.md)
- [ ] [`InsertInline`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/edits/insert-inline.md)
- [ ] [`ReplaceInline`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/edits/replace-inline.md)
- [ ] [`DeleteInline`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/edits/delete-inline.md)

### <a name='Works'></a>Works

Node types, derived from `CreativeWork`, that can be part of the content of a document:

#### <a name='Blockworks'></a>Block works

- [ ] [`Claim`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/works/claim.md)
- [ ] [`Comment`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/works/comment.md)
- [ ] [`Figure`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/works/figure.md)
- [ ] [`Table`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/works/table.md)

#### <a name='Inlineworks'></a>Inline works

- [ ] [`ImageObject`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/works/image-object.md)
- [ ] [`AudioObject`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/works/audio-object.md)
- [ ] [`VideoObject`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/works/video-object.md)

#### <a name='Datavalues'></a>Data values

Node types which can be part of `CodeChunk.outputs`, `CodeExpression.output` etc. The atomic primitive types (e.g. `Boolean`, `Number`) only need simple UI to distinguish them from text. The compound primitive types (`Array` and `Object`) need more complex UI that allow navigation for larger output node (e.g. a tree nav for a large, nested `Object`).

- [ ] [`Boolean`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/boolean.md)
- [ ] [`Integer`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/integer.md)
- [ ] [`UnsignedInteger`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/unsigned-integer.md)
- [ ] [`Number`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/number.md)
- [ ] [`Array`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/array.md)
- [ ] [`Object`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/object.md)

#### <a name='Datavalidators'></a>Data validators

Node types which can be a `Parameter.validator` or `DatatableColumn.validator` for specifying the type and range of values that can be in `Parameter.value` and `DatatableColumn.values` respectively:

- [ ] [`ArrayValidator`](array-validator.md)
- [ ] [`BooleanValidator`](boolean-validator.md)
- [ ] [`ConstantValidator`](constant-validator.md)
- [ ] [`DateTimeValidator`](date-time-validator.md)
- [ ] [`DateValidator`](date-validator.md)
- [ ] [`DurationValidator`](duration-validator.md)
- [ ] [`EnumValidator`](enum-validator.md)
- [ ] [`IntegerValidator`](integer-validator.md)
- [ ] [`NumberValidator`](number-validator.md)
- [ ] [`StringValidator`](string-validator.md)
- [ ] [`TimeValidator`](time-validator.md)
- [ ] [`TimestampValidator`](timestamp-validator.md)

### <a name='Other'></a>Other

Node types needed because they are part of the properties of other node types (e.g. `List.authors`):

- [ ] [`Person`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/other/person.md)
- [ ] [`Organization`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/other/organization.md)
- [ ] [`SoftwareApplication`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/other/software-application.md)
- [ ] [`AuthorRole`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/works/author-role.md)

**Comment by kusalekanayake** [comment]
TODOs: Look at plugins, how to view, add, remove plugins.

**Comment by kusalekanayake** [comment]
The start of the plugin screen.
![plugins](https://github.com/stencila/stencila/assets/16539995/ce436498-07e4-4054-a897-20dfb074c937)
<img width="870" alt="image" src="https://github.com/stencila/stencila/assets/16539995/f9dc3e96-6fc7-4e1f-bbc9-1cce26fde9cd">

**Comment by kusalekanayake** [comment]
Settings/config.

![settings 2](https://github.com/stencila/stencila/assets/16539995/10131665-87a2-4442-837b-9cba25c5f1d8)

**Comment by kusalekanayake** [comment]
Status icon
![sync icon](https://github.com/stencila/stencila/assets/16539995/012c8380-f6df-4eb4-957b-70806b6acb38)

**Comment by kusalekanayake** [comment]
@nokome these are the two designs for the visual view of the for loop. How close are they to your expected representation?
![SpaceFor](https://github.com/stencila/stencila/assets/16539995/6de0fcb1-2100-4714-aa1d-07c10673b867)


![CompactFor](https://github.com/stencila/stencila/assets/16539995/e81bfebf-655f-4ed9-8e8b-d2703843ab3b)

**Comment by kusalekanayake** [comment]
This is the view for an IF statement.
![Visual view IF](https://github.com/stencila/stencila/assets/16539995/6bf2f093-23e6-4e9f-843c-70d234668285)

**Comment by kusalekanayake** [comment]
I still need to add in the right info box to show the surrounding/contextual information like last run, warnings, dependencies?, other actions.

**Comment by nokome** [comment]
Thanks @kusalekanayake. These look good. Some opinions:


### For block

- I think aspects of the two options should be combined.

- I like the "Iterations" header of the first - it should have a dropdown caret on the right so that the iterations can be folded away or expanded.

- I think each iteration should have a its own header, like in the second (but less weighty than the parent "Iterations" header) and drop the "Variable" from "#1 Variable". Each iteration could have a dropdown caret but that is maybe getting too busy.

- The content in each iteration should not have any border and have minimal margin (as in the second) but a slight coloured mask to indicate that it is not editable.

- The top section needs to be less "formy". I think that the "item_index" (the `variable` property), the "range(....)" (the `code` property), and the language selector should go into the top most header and replace "For Loop Block". It will make it a lot more compact.

- The `content` to be repeated should be just below the main header with no mask - just like the rest of the content in the document but contained within the `ForBlock`. Think about a user selecting some content, for example a paragraph and a code chunk that produces a figure, and right clicking, selecting "Wrap into for block" and then having this UI appear where they can then define what to repeat over etc.

### If block

- As with the `ForBlock` I think we should try to coalesce the code and language selector of the first clause into the top most header to take up less vertical space in the doc.

- No need for the semicolon before the language selector.

- The grab handles could be smaller.

- Consider fold/expand for each clause.

- The user needs a way to delete a clause. A delete icon next to the grab handle?

- No need for the shading around the content of each clause.

- We need to think about which clause is currently active - i.e. the one that will be shown in the rendered in the doc. Some options:

    - darker shading of the clause header
    - a circle around the icon of the clause that is active
    - both of the above
    - lighter shading of content in inactive clause content

- When the user starts to type in the empty `code` of the last clause it should change from `else` to `elif`.

- There should be a footer with an icon on the left to add a new clause.

> I still need to add in the right info box to show the surrounding/contextual information like last run, warnings, dependencies?, other actions.

I'm having doubts that having a separate info box is the right place for this. It feels "jumpy". We've had dropdowns for this in the past. e.g. a status icon which you can click on to see dependencies. I'll see if I can dig some examples out of the attic.

**Comment by kusalekanayake** [comment]
Have updated both the for and if based on notes. It's getting a little difficult to denote the active statement for if amongst the highlighted heads. Also trying to communicate editable text vs non-editable text.

I had the same thoughts with how else would operate as an else until something was typed in the clause section to which it would then switch to an else if.

![Visual view for 2](https://github.com/stencila/stencila/assets/16539995/9ce64713-a243-460b-9725-35ab05f10305)

![Visual view if 2](https://github.com/stencila/stencila/assets/16539995/bf26a4e3-68c8-400d-a450-69d2ab681421)

**Comment by kusalekanayake** [comment]
Have updated the way these specific blocks look. To contain the same fodder that most other blocks may contain.
![Bottom panel-1](https://github.com/stencila/stencila/assets/16539995/906f4f98-6507-4802-9b6c-f3e3e7c9489b)
![Bottom panel](https://github.com/stencila/stencila/assets/16539995/3eb6e579-8c3f-4110-a6f1-2294766d80ff)
![Visual view-1](https://github.com/stencila/stencila/assets/16539995/23057cf5-12e2-4d45-830a-53939c797326)
![Visual view](https://github.com/stencila/stencila/assets/16539995/77c25670-7af9-4e68-9e80-ab2d7ca3ff35)

![if block prose](https://github.com/stencila/stencila/assets/16539995/205baaa7-5f4c-4bfe-903c-9aa4376136f4)

**Comment by kusalekanayake** [comment]
Hover info on visual view!

![hover info visual view](https://github.com/stencila/stencila/assets/16539995/ade87383-904d-45dc-8ac6-869824b9ceed)

**Comment by nokome** [comment]
There are plenty of useful screenshots and discussion in this issue but closing because a lot of it has been superseded / done.
