### ISSUE TITLE
fix(`<stencila-ui-node-execution-details>`): make collapsable and improve styling

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2124]
## Background

The `<stencila-ui-node-execution-details>` component is a container for some of the properties of node types derived from [`Executable`](https://github.com/stencila/stencila/blob/main/docs/reference/schema/flow/executable.md). It appears at the top of executable node types. e.g. for `CodeChunk`

![image](https://github.com/stencila/stencila/assets/1152336/dcd26129-0463-41b3-8035-6fc9588b1e99)

There is a preliminary implementation of this component:

https://github.com/stencila/stencila/blob/bbe35ecb008cb630c0f7249eb70d09fee7badb34/web/src/ui/nodes/properties/execution-details.ts#L51-L68

Which adds some properties that were not included in the designs (I suspect unintentionally) and excludes some (e.g. dependencies) because we do not have a re-implementation of those.

This preliminary rendering looks like this for unexecuted code chunks:

![image](https://github.com/stencila/stencila/assets/1152336/f16b41ec-137b-4f0d-83f0-a85848637041)

and like this when executed:

![image](https://github.com/stencila/stencila/assets/1152336/ee1d4ab9-6378-4155-9669-8db03c67cad9)

## Tasks

- [x] Make these details collapsible so that the user can hide them if they wish
- [x] Make the layout more vertically compact
- [x] Improve tooltip placement

@simonwinter could you work on this please, possibly incorporating your work-in-progress around this, and submit as a PR. You might have to work on the child elements e.g. `<stencila-ui-node-execution-ended>` to achieve designed look  but be aware that there will be other issues to improve some of those.
