### ISSUE TITLE
fix(node authors): improve rendering of `<stencila-ui-node-authors>` as per designs

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2132]
## Background

I've done some refactoring of the rendering of the `authors` property. The schema is flexible (attempting to stay consistent with schema.org while also allowing for more detail that we require), but this makes consistently rendering authors as per the designs complicated. To solve this I have created `<stencila-ui-node-author>` which has some rationale for its existence:

https://github.com/stencila/stencila/blob/493b71c58051cb030776e27cfd3e6cb197e133ec/web/src/ui/nodes/properties/author.ts#L7-L25

But currently very little styling (I just wanted to check all the necessary props were getting passed down):

![image](https://github.com/stencila/stencila/assets/1152336/e7080f27-b1e4-460e-bba4-f8270692ed2c)

Whereas the designs are like this:

![image](https://github.com/stencila/stencila/assets/1152336/b726325f-d0fd-4685-a87f-2d4afddec474)

To avoid bloating documents too much the author information for each node is kept minimal. It is envisaged that when we will store more complete user information for each author in the `authors` property of the `Article` and use `id` to fetch that to add things like affiliations. Maybe. Anyway, for now, there is limited info available.

## Tasks

- [x] I recommend using http://localhost:9000/nodes/paragraph/paragraph.json?view=split as a test - it has various permutations of the different author types.
- [x] Style `<stencila-ui-node-author>` and `<stencila-ui-node-authors>` as per the designs noting that not all aspects of the design will be possible (e.g specific avatars for people)
- [ ] Factor out most of `<stencila-ui-node-execution-duration>` into `<stencila-ui-node-timestamp-property>` in `ui/nodes/properties/generic/` so we can reuse it's updating humanized time for execution duration and for the timestamp associated with each author.
- [ ] There shouldn't be a need to touch the files in `web/src/nodes`, only those in `web/src/ui/nodes`. However, please review `AuthorRole.getAuthor()` - it seems to work but feels a little brittle and could do maybe do with some minor refactoring (e.g. factoring out the multiple `inner.tagName.toLowerCase()`).

**Comment by simonwinter** [comment]
> Style <stencila-ui-node-author> and <stencila-ui-node-authors> as per the designs noting that not all aspects of the design will be possible (e.g specific avatars for people)

In this specific case, I suggest we use the familiar pattern of using the initial from the users first name. 

An issue in the future could be to look at unique colour values for each user based on their name or id or something.

**Comment by nokome** [comment]
> In this specific case, I suggest we use the familiar pattern of using the initial from the users first name.
> 
> An issue in the future could be to look at unique colour values for each user based on their name or id or something.

That's a good idea.
