### ISSUE TITLE
feat(code chunk outputs): add a `stencila-ui-node-outputs` component and components for common output types e.g. `stencila-string`, `stencila-image-object` etc

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2145]
## Problem

The `<stencila-code-chunk>` component needs a UI component to display its outputs. This is current unimplemented:

![image](https://github.com/stencila/stencila/assets/1152336/65c41f0d-3327-4d10-a247-a699e91b2059)

Currently, the designs for this are component are minimal and don't show how to display the actual outputs:

![image](https://github.com/stencila/stencila/assets/1152336/5d3f34ac-4f1a-40bb-a1be-899a88641dd3)

The `outputs` of a code chunk can be any `Node` type but will usually be a primitive type (as listed in "Data values" in https://github.com/stencila/stencila/issues/2027), an `ImageObject` (e.g. a plot) or a `Datatable` (tabular data with columns having specific types).

The `examples/kernels/code-chunk/output-types-r.json` and `examples/kernels/code-chunk/output-types-python.json` have examples of all these output types and illustrate how display of `outputs` need to be improved.

### Each output node needs to be presented separately

This is actually six separate primitive outputs from the one `CodeChunk` but they are all on the same line:

![image](https://github.com/stencila/stencila/assets/1152336/251ebb33-5ca2-4c9a-8a26-c5dc8d6d95e9)

###  Datatables are not displaying at all because on how they are encoded to DOM HTML

![image](https://github.com/stencila/stencila/assets/1152336/c2fe20ff-656d-472e-875f-837e2f7d460e)

### Images are shown at full size and not constrained to be within the node card

![image](https://github.com/stencila/stencila/assets/1152336/3ce8ab05-9f6c-4ed1-9ef9-e01028ebdd9a)

## Tasks

- implement a collapsible `<stencila-ui-node-outputs>` component (similar to `stencila-ui-node-messages` and `stencila-ui-node-authors`)
- implement components for common node types found in code chunk `outputs`:
  - Primitive node types
     - [ ] [`Boolean`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/boolean.md)
     - [ ] [`Integer`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/integer.md)
     - [ ] [`UnsignedInteger`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/unsigned-integer.md)
     - [ ] [`Number`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/number.md)
     - [ ] [`String`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/string.md)
     - [ ] [`Array`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/array.md)
     - [ ] [`Object`](https://github.com/stencila/stencila/tree/main/docs/reference/schema/data/object.md)
  - [ ] `ImageObject`
  - [ ] `DataTable`

**Comment by nokome** [comment]
Done in #2150 (and others)
