### ISSUE TITLE
meta(planning): priorities and ordering of task 7-24 May

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2209]
This provides some prioritization and ordering of tasks to be done over the next couple of weeks. They are roughly grouped by week. Must haves for each week are indicated with an asterisk. There are only a few must haves at this stage - overall things are in an OK state for happy path demos. However, the more of the other tasks can be completed the more impressive and smoother demos and user testing can be 🌈 .

This will evolve over time. e.g after reviewing draft PRs.

I've added handles for things that a most suited to one person. Please add your name when you want to take something on and tick the box when its done.

### May 7 - 10

- [x] shading of `<stencila-authorship>` elements based on `provenance` attribute #2206 B @mike-parkin in progress 

- [x] tooltips for each `<stencila-authorship>` run showing the `count` and `provenance` #2206 C

- [x] shading of code within `<stencila-code-chunk>` based on the `code-provenance` attribute  #2206 F @mike-parkin done in #2212

- [x] display `<div slot=provenance>` in node cards #2206 A @simonwinter

- [x] get sketches of diagrams to Pep @nokome 

- [x] *update preview panel as document updates @nokome

- [ ] #2239

- [x] add debouncing to the update task in `lsp/src/text_document.rs` so that changes are affected as edits @nokome 

- [x] *allow configuration of the author in vscode extension and pass through so it can be used in patches @nokome 

- [ ] #2242

- [x] add a retry code lens for suggestions (rerun parent instruction)

- [ ] #2243

- [ ] add `assistant-perplexity` for reduced latency during demos #1898 @nokome

- [x] add an `insert-para` builtin task specialized assistants for inserting one or more paragraphs (`insert-blocks` is too generic and if not instructed specifically enough can produce list, tables etc) @brettc 

- [x] *write demos as walkthroughs see [here](https://github.com/stencila/stencila/tree/main/vscode#writing-walkthroughs)  @brettc 

- [ ] change order of specialized assistants `delegates` based on relative performance for the task e.g Claude-3 vs GPT4 vs Groq/Lllama-3 @brettc 

- [x] fix issue with `insert-math-block` assistant related to ser/de-ization of `Cord` (?) @nokome 

- [ ] fix issue with executing R (and other) kernels from within vscode (need to set document `home`?) (this is an issue for me using `asdf` and with how PATH is set)

### May 13 -17

- [ ] styling of status decorations in VSCode extension [see TODOs here](https://github.com/stencila/stencila/blob/441612823de1b58c5448241a75977ffd35569f28/vscode/src/extension.ts#L200-L264) @simonwinter `in progress`

- [x] update `stencila/stencila` README @nokome

- [ ] CI for `stencila/writer`: tests plus release build. (follow patterns used in the repo for uploading build artifacts, or vscodium has better approach?)

- [ ] update `stencila/writer` README etc @nokome

- [x] in the dynamic view add a way for the user to toggle the visibility of (a) node "chips", (b) node cards, (c) machine influence shading. (a) and (b) could be on the same cycling toggle `nothing visible (except on hover) -> chips visible -> all cards expanded -> nothing visible`, (c) is probably best as a separate toggle/switch. A small sticky button/switch for each of these in the top corner?

- [ ] in the dynamic view add a way for users to switch between themes

- [ ] when the node card is open and the authors are visible, when hovering over a `<stencila-authorship>`, the associated authors are highlighted #2206 D

- [ ] when the node card is open and the authors are visible, when hovering over a `<stencila-author>` all the `<stencila-authorship>` elements that the author belongs to are highlighted (the inverse of the above). #2206 D

- [x] execution message tooltips on code chunks should use Inter font https://github.com/stencila/stencila/issues/2229

**Comment by nokome** [comment]
Collecting some thoughts here for a UI/UX review (Friday?):

###  Text provenance

![image](https://github.com/stencila/stencila/assets/1152336/3ddef98b-22e5-48fa-8c91-8b232849bb37)

- darkest blue shading too dark
- tool tip text more descriptive: e.g. "3 authors, machine written, human edited, human verified twice"
- tool tip feels heavy, could be shaded dark blue

**Comment by nokome** [comment]
Continuing to collect more small UI/UX fixes here (rather than create new issues for now)...

## Instruction Block

![image](https://github.com/stencila/stencila/assets/1152336/681771a7-fd9a-449f-a675-3e96a8e0437e)

- [ ] the pills for provenance are stacked vertical rather than being horizontal
- [ ] no horizontal line between Provenance and Chat to separate them
- [ ] when made a little narrower, the status details collapse to a single column and take up a lot of vertical space, just wrapping or two or three columns would feel less drastic

![image](https://github.com/stencila/stencila/assets/1152336/ccd11ed9-01f7-47df-ae26-8d43e5e6f44a)
 
## Authors

Similar to the above, there is a big change in the layout of authors when the screen is made narrower e.g.

![image](https://github.com/stencila/stencila/assets/1152336/3b9307e4-f993-4534-9ab7-abf2c2751c65)

vs the following (this needs to be more compact vertically, maybe by just dropping or wrapping under the time)

![image](https://github.com/stencila/stencila/assets/1152336/8593bbe9-046d-4af1-a653-8aca5c9750fe)

**Comment by nokome** [comment]
I've added authors and code provenance to other code-based nodes including `CodeBlock` & `MathBlock`, `StyledBlock` and their inline counterparts. One result of this is that AI generated `CodeBlock` (example code) is highlighted:

![image](https://github.com/stencila/stencila/assets/1152336/889b2961-6df3-4b0e-9cb2-f366ff80d646)

Also another thing that bothers me is that the `CodeBlock` does not have have a border, or any indication of what language it is.

**Comment by nokome** [comment]
Closing now as most of these have been completed or are in an existing issue.
