### ISSUE TITLE
docs(walkthroughs): checklist and planning

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2434]
### Which component?

Stencila VSCode extension

### What do you think needs to be improved?

We have invested time in establishing walkthroughs as a primary onboarding tool for new users (and as a reference for users who have already onboarded). This issue provides an checklist for building on this investment by writing several more walkthroughs.

Walkthroughs are actually Stencila `Article`s (with some introductory content followed by a single `Walkthrough` node with a number of `WalkthoughSteps`). Because of this many of the walkthroughs can be written in a single format and then converted to the other supported (text-based) formats (e.g. written in `.smd` and then converted to `.myst` and `.qmd`).

Some walkthroughs will need to be written separately for each format because they contain format specific content. For example, the current `docs/walkthroughs/command-syntax.smd` describes the peculiarities of the `:::` semicolon fences in Stencila Markdown and so should not be converted to MyST and Quarto Markdown, where these do not apply. Instead we, need to write a `command-syntax.myst` etc file for each supported format. The checklist indicates this below using separate items for each format.

### Meta

- [ ] Add a `docs/walkthroughs/README.md` to give guidelines on how to write walkthroughs
- [ ] Publish walkthroughs as part of our documentation site stencila.io/docs/ (requires #2383)

### AI Commands

- [ ] Introduction and syntax
   - [x] SMD `command-syntax.smd`
   - [ ] MyST
   - [ ] QMD (requires QMD support to be added first) 
 - [ ] Create command
 - [ ] Edit command
 - [ ] Fix command
 - [ ] Describe command

### Node types

Walkthroughs which aim to show the user how to create various types of content, including by using AI commands.

- [ ] General static document structure e.g. headings, paragraph, inline marks e.g. strong, superscript
- [ ] Executable code (block and inline)
- [ ] Figures and tables (labels, captions etc)
- [x] Math (block and inline) `math.smd`
- [x] Mermaid diagrams `mermaid.smd`
- [ ] `ForBlock` (at this stage mainly for users wanting to write their own prompts)
- [ ] `IfBlock` (as above)
- [ ] `RawBlock`
- [ ] `StyledBlock`

### Kernels

Walkthroughs which go into details about the main programming language kernels including which binary/environment is used, and how different objects are represented within a document.

- [ ] Python
- [ ] R
- [ ] JavaScript
