### ISSUE TITLE
Basic Sheet Editing #1

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#337]
A summary of all issues related to basic sheet editing that we want to address in a first iteration:

## Selection
- [x] Select a single cell #341
- [x] Select a range #342
- [x] Selecting rows and columns #343
- [x] Changing the Selection via Keyboard #344
- [ ] Select All #345

## Manipulation
- [x] Entering and Editing cells #340
- [x] Clearing cells #339
- [x] Overwriting a cell via typing #338
- [x] Inserting rows and columns #346
- [x] Deleting rows / columns #347

## Copy'n'Paste
