### ISSUE TITLE
Sheets : a todo list

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#85]
Things we need to do to get a basic demo running on the hub.

In the JS front-end:

- [x] In `web/sheet/model/Sheet` have an interface to a `model/Spread` class (to mirror the class in the C++ back-end) which will be used to update a cell value when its contents change. The only method needed for the `Spread` at this time is `update(id,content)` where id is for e.g. `AB34` and `content` could be for example `= 2*A3`. The method is called when a cell content's change and will return an object with all the cell values that need to be changed e.g 

```
{
   "AB34": "43",
   "Y20": "123"
}
```

- [x] In `SheetEditor` (?) we need to call this `update` method when user moves out of a cell they have changed.

- [x] Extract the address of the sheet from `<head>` like we do for stencils. 

- [x] Add an activate button to start a new session

In C++/R/Python back-end:

- [x] Extract meta attributes (e.g. title, description) ~~without needing a session~~

- [x] Implement graph dependency analysis

- [x] Store a sheet's spread as `sheet.RData` (R) or `sheet.pkl` (Python). This will be used during`compile()` via the spread method `get()` to create an `index.html`. (For security reasons, we always want `index.html` to be created on the hub, not commited into the repo. But we also don't wan't to have to `update()` the sheet each time this is done. Having persistence of sheet variables allows for this but will obviously require the pickle file to be commited and a host language session be created to do `compile()`)

On the hub:

- [x] Fix bug with requests going from `director` to `worker`

- [x] Sessions should time out after inactivity

**Comment by nokome** [comment]
@oliver---- and @michael : I did jobs 1,2 & 3 above in commit e2e3ae8. But some of it felt pretty hacky and I'm not sure I put things in the right place. This comment is just to point to that commit as a place that probably needs some code review from you guys - but only when you have time. Lets wait until we all have at least a day or two to focus on it. In the meantime, I am going to address the remaining todo items in this list...

**Comment by michael** [comment]
Hey! That looks impressive! :) I just saw the video. Are you planning to post this publicly?

I think it would be the best to put ourselves into Stencila mindset for day or two where we all work together with the goal of getting a demo live. I think we should do a mission briefing first and discuss how the sheet editor should be integrated into the whole Stencila app, or you just want to have it as an isolated example for now?

Can you give me fool-proof step by step instructions on how to run the demo locally including bringing up the backend / r-session through docker?

**Comment by michael** [comment]
Regarding timing..  would it be too late to push this to after Christmas? We are in a good flow with our realtime editing spike and are working through the backlog for a beta 3 release that's coming in the next days. It will have lots of fixes and also a bunch of API cleanups. So maybe it would be good to wait for that so we can base the Stencila work on it?

**Comment by oliver----** [comment]
@nokome 
just watched your video. Congratulations! that is reaaaally impressive!
I will take a look at your work next week between xmas and new year.

Cheers

**Comment by nokome** [comment]
@michael and @oliver---- : thanks for the feedback - and your help!

>  I just saw the video. Are you planning to post this publicly?

No not at this stage. Plan to do a proper initial release with docs, video etc in mid to late Feb.

> put ourselves into Stencila mindset for day or two where we all work together with the goal of getting a demo live. I think we should do a mission briefing first ...

Yes, I agree, that is what I had in mind. I will work to get a live demo running on http://stenci.la in the next 2-3 weeks. That will allow everyone to play with it and see what the problems are and allow us to prioritize.

> discuss how the sheet editor should be integrated into the whole Stencila app, or you just want to have it as an isolated example for now?

I envisaged that each Stencila "component" (i.e. Stencil, Theme, Sheet...) would be a single page app. Like in Google docs. That is how it is currently set up - each component has it's own URL and use either `stencil.js` or `sheet.js`. But yes there is some integration and code sharing to be done - which I started a bit in the above commit.

> Can you give me fool-proof step by step instructions on how to run the demo locally including bringing up the backend / r-session through docker?

On Linux you can just `make r-install` and then `stencila-r web/examples/b update view ...`. But I have not yet built a new docker image with the sheets branch. I need to do it for the live demo anyway. So, I'll let you know when it is done.

> Regarding timing.. would it be too late to push this to after Christmas? ... beta 3 release ... So maybe it would be good to wait for that so we can base the Stencila work on it?

Yes, I think it is best to wait until the live demo and Substance beta 3 are done. I am thinking mid to late January. How does that suit you?

**Comment by nokome** [comment]
@michael : I have updated the Docker image for R so that it has the sheets stuff. So you should be able to do this

```sh
docker pull stencila/ubuntu-14.04-r-3.2
docker run --detach --publish=7373:7373 stencila/ubuntu-14.04-r-3.2 stencila-r demo/sheets/iris update serve ...
```

and then open your browser to `http://localhost:7373/demo/sheets/iris/` (give it a few seconds to clone the sheet's repo). That will use the bundled JS and CSS from S3.

If you want to work on the JS or SCSS then start the Node server and it proxy through to 7373:

```sh
cd web
npm start
```

and

**Comment by michael** [comment]
Thank you! Worked for me. Except for some app-specific bugs. Should I see rendered chart images already?

**Comment by nokome** [comment]
Great. You should have images already and be able to change cell values and have them updated.

**Comment by michael** [comment]
I can change cell values and see other vals update. But for the image i see this:

![image](https://cloud.githubusercontent.com/assets/2931/11976945/a4581792-a97d-11e5-907f-232387a0f4f8.png)

**Comment by nokome** [comment]
Aahh. In a recent commit I changed 'image-url' to 'ImageFile' but you are only getting that change in the front-end JS not in the backend R session. Checkout commit e3a3d57e to get it to work. I will let you know when I have updated the back end and you can do another `docker pull`

**Comment by nokome** [comment]
The basic demo is now running on the hub and pretty much everything here is done. So closing this now and creating separate issues for upcoming sprint
